# -*- coding: utf-8 -*-
"""async_readback_distribution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15XdVErzDCpHHZewXoLr0ePUS4xGEFjlG
"""

import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns

with open("output.json") as f:
    data = json.load(f)

starts = np.asarray(data['starts'])
ends = np.asarray(data['ends'])

latencies = ends - starts

# The first few and the last few entries are usually unreliable.
latencies = latencies[5:-5]

# Convert the latencies in seconds to milliseconds
ms_latencies = 1000.0 * latencies

plt.figure(figsize=(10,10))
sns.histplot(data=ms_latencies, bins=100, kde=True)

plt.title(f"Latencies of {len(ms_latencies)} async readbacks")
plt.xlabel("Latency (ms)")
plt.savefig('output.png', dpi=100)
plt.show()
