#include "/Engine/Public/Platform.ush"

RWTexture2D<float4> term1;
// RWTexture2D<float4> term2;
Texture2D<float4> term2;
RWTexture2D<float4> result;



[numthreads(N_THREADS_X, N_THREADS_Y, 1)]
void eWaveCompute(uint3 id : SV_DispatchThreadID) {
  float4 a = term1[id.xy];
  float4 b = term2[id.xy];
  float4 r = a + b;
  // r.y = -r.y b;
  r.a = 1.0;
  result[id.xy] = b; //float4(id.x, id.y, 0.0, 1.0);
  //result[id.xy] = float4(0.2 * id.x + 0.1, 0.0, 0.0, 1.0);
}