#include "/Engine/Public/Platform.ush"

/* Vertex Shader */

void MainVertShader(float4 InPosition : ATTRIBUTE0, float2 InUV : ATTRIBUTE1, out float2 OutUV : TEXCOORD0, out float4 OutPosition : SV_POSITION) {
	OutPosition = InPosition;
	OutUV = InUV;
}

/* Fragment Shader */

void MainFragShader(in float2 uv : TEXCOORD0, out float4 OutColor : SV_Target0) {
	// OutColor = float4(uv.x, uv.y, 0.0, 1.0);
	OutColor = float4(1.0, 0.0, 0.0, 1.0);
}
